services:
  frontend:
    build: ./frontend
    # image: cyriellethomas/flowee-deploy-client:staging-latest
    platform: linux/x86_64
    expose:
      - 5173
    command: sh -c "npm run build && npm run preview"
    restart: unless-stopped
    volumes:
      - web-client-build:/app/dist
    environment:
      - NODE_ENV=production  
    # restart: always
  backend:
    build: ./backend
    # image: cyriellethomas/flowee-deploy-server:staging-latest
    platform: linux/x86_64
    # command: sh -c "npm run prod"  
    restart: unless-stopped
    expose:
      - 4000
    environment:
      - NODE_ENV=production
      - SERVER_PORT=4000
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
 

  db:
    image: postgres:16
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  nginx:
    image: nginx:1.21.3
    depends_on:
      - backend
      - frontend
    restart: always
    ports:
      - ${GATEWAY_PORT_STAGING:-8004}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx

volumes:
  web-client-build:
