name: jest testing

on:
  pull_request:
    branches: [dev]
    
jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies and run tests
        run: |
          cd backend
          npm install
          npm test
