name: vitest testing

on:
  push:
    branches: [dev]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches: [dev]

jobs:
  front-vitest-tests:
    name : Run Vitest Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Check installed dependencies
        run: npm list --depth=0


      - name: Run Vitest tests
        run: cd frontend && DEBUG=apollo:* npm run test